version: "2"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - holding
    ports:
      - 3306:3306
  nginx:
    image: nginx
    restart: always
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - 88:80
    networks:
      - holding
  php:
    build: ./docker/php
    restart: always
    volumes:
      - ./app:/app:rw
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    links:
      - db
    env_file:
      - .env
    networks:
      - holding
networks:
  holding:
    driver: bridge